apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dotnet14824newxx
  janus-idp.io/tekton: dotnet14824newxx
  backstage.io/kubernetes-id: dotnet14824newxx
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dotnet14824newxx
resources:
- deployment.yaml
- route.yaml
- service.yaml
