apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dotnet14824newxx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dotnet14824newxx 
  name: dotnet14824newxx
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dotnet14824newxx 
